# Generated by Django 3.2.6 on 2021-09-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carstore', '0002_alter_record_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['carmodel']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
