# Generated by Django 3.2.6 on 2021-09-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carstore', '0004_auto_20210923_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
