# Generated by Django 3.2.6 on 2021-09-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carstore', '0005_auto_20210923_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
