# Generated by Django 3.2.6 on 2021-09-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carstore', '0006_alter_carmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
