# Generated by Django 3.2.6 on 2021-08-23 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carstore', '0002_alter_record_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.employee')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.firm')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carstore.carmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carstore.record')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFirmsRelation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.employee')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.firm')),
            ],
        ),
    ]
